version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Initialize venv / Install deps
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          name: Linting
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest

  containerize:
    docker:
      - image: cimg/python:3.10.2
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Containerize
          command: |
            echo "$AZURE_PASSWORD" | docker login oclettings.azurecr.io --username $AZURE_USERNAME --password-stdin
            docker build --tag p13-oclettings:${CIRCLE_SHA1} .
            docker push oclettings.azurecr.io/p13-oclettings

  deploy-to-azure:
    docker:
      - image: cimg/python:3.10.2
    resource_class: medium
    steps:
      - setup_remote_docker
      - run:
          name: Deployment
          command: |
            echo "$AZURE_PASSWORD" | docker login oclettings.azurecr.io --username $AZURE_USERNAME --password-stdin
            docker images

workflows:
  main:
    jobs:
      - build-and-test
      - containerize:
          requires:
            - build-and-test